version: "3.9"
services:
  dind:
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: ["--host=tcp://0.0.0.0:2375", "--tls=false"]
  server:
    image: baruh/aocjudge-server
    depends_on:
      - dind
    environment:
      DOCKER_HOST: tcp://dind:2375
      AOCJUDGE_HOST: 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
